# Changes here will be overwritten by Copier
_commit: v0.2.11
_src_path: git+https://gitlab.ewi.tudelft.nl/reit/python-package-template
coc: our_coc
email: s.wacker@gmail.com
environment_manager: uv
full_name: Sören Wacker
host: gitlab.ewi.tudelft.nl
license: GPL
min_python_version: '3.10'
org: sdrwacker
project_name: slurm-usage-history
project_short_description: A great package.
python_name: slurm_usage_history
typing: no_typing
url: https://gitlab.ewi.tudelft.nl/sdrwacker/slurm-usage-history
